export type PastLifeRarity = "normal" | "rare" | "epic" | "legendary";

export type PastLifeCamp = "power" | "wealth" | "love" | "jianghu" | "immortal" | "underworld";

export type PastLifePreset = {
  id: string;
  camp: PastLifeCamp;
  rarity: PastLifeRarity;
  title: string;
  rank: string;
  keywords: string[];
  triggerHint: string;
  shortText: string;
  shareText: string;
};

export const CAMP_LABELS: Record<PastLifeCamp, string> = {
  power: "权谋系",
  wealth: "财帛系",
  love: "桃花系",
  jianghu: "江湖系",
  immortal: "仙门系",
  underworld: "地府系",
};

export const RARITY_LABELS: Record<PastLifeRarity, string> = {
  normal: "普通",
  rare: "稀有",
  epic: "史诗",
  legendary: "传说",
};

export const RARITY_PERCENT: Record<PastLifeRarity, string> = {
  normal: "命格池约 18%–31%",
  rare: "命格池约 6%–12%",
  epic: "命格池约 1.6%–4.9%",
  legendary: "命格池约 0.3%–0.9%",
};

// ─── 72 Presets ───

const PRESETS_RAW: Array<{
  id: string;
  camp: PastLifeCamp;
  rarity: PastLifeRarity;
  title: string;
  rank: string;
  keywords: string;
  shortText: string;
  shareText: string;
}> = [
  // Power 12
  {
    id: "P01",
    camp: "power",
    rarity: "legendary",
    title: "失眠摄政王",
    rank: "幕后最高话事人",
    keywords: "控场,抗压,嘴硬,晚成",
    shortText:
      "你前世不是皇帝，是让皇帝别乱来的那个人。今生最怕的不是没机会，是别人低估你能把烂局收拾成局。",
    shareText: "你朋友测出了「失眠摄政王」\n别人低估他能把烂局收拾成局。\n你会是什么前世身份？",
  },
  {
    id: "P02",
    camp: "power",
    rarity: "epic",
    title: "冷宫 KPI 女官",
    rank: "宫廷中层管理",
    keywords: "清醒,记账,执行,克嘴",
    shortText: "你前世在冷宫搞绩效，今生在人间看穿职场。你不是不争，是嫌那群人段位太低。",
    shareText:
      "你朋友测出了「冷宫 KPI 女官」\n在冷宫搞绩效的人，来人间看穿职场。\n你会是什么前世身份？",
  },
  {
    id: "P03",
    camp: "power",
    rarity: "rare",
    title: "王府礼法总管",
    rank: "贵族制度管理员",
    keywords: "规矩,体面,资源,秩序",
    shortText: "你前世管的是体面，今生烦的是没边界的人。你适合在混乱里立规矩，然后悄悄掌权。",
    shareText: "你朋友测出了「王府礼法总管」\n适合在混乱里立规矩，悄悄掌权。\n你会是什么前世身份？",
  },
  {
    id: "P04",
    camp: "power",
    rarity: "epic",
    title: "前朝嘴硬御史",
    rank: "朝堂嘴炮核心",
    keywords: "正义,毒舌,硬骨,反骨",
    shortText: "你前世上朝不是为了升官，是为了让蠢人闭嘴。今生别总忍，你的攻击性用对了就是护身符。",
    shareText: "你朋友测出了「前朝嘴硬御史」\n上朝不为升官，为了让蠢人闭嘴。\n你会是什么前世身份？",
  },
  {
    id: "P05",
    camp: "power",
    rarity: "normal",
    title: "宫廷档案校对官",
    rank: "机密文书小吏",
    keywords: "细节,记忆,谨慎,吐槽",
    shortText: "你前世靠改错别字保住一堆人的脑袋。今生对细节敏感，不是挑剔，是命里带审稿。",
    shareText: "你朋友测出了「宫廷档案校对官」\n靠改错别字保住一堆人的脑袋。\n你会是什么前世身份？",
  },
  {
    id: "P06",
    camp: "power",
    rarity: "rare",
    title: "密旨传话太监",
    rank: "危险信息中转站",
    keywords: "嘴快,情报,察言,求生",
    shortText: "你前世专门传不能写下来的话。今生你看人说话听潜台词，比对方本人还明白。",
    shareText:
      "你朋友测出了「密旨传话太监」\n专门传不能写下来的话，比本人还明白。\n你会是什么前世身份？",
  },
  {
    id: "P07",
    camp: "power",
    rarity: "epic",
    title: "边境临时节度使",
    rank: "危机接盘侠",
    keywords: "硬扛,换局,孤勇,杀伐",
    shortText: "你前世接的全是烂摊子，今生也总在关键时刻被推上台。别怕，你就是乱世配置。",
    shareText:
      "你朋友测出了「边境临时节度使」\n接的全是烂摊子，关键时刻被推上台。\n你会是什么前世身份？",
  },
  {
    id: "P08",
    camp: "power",
    rarity: "normal",
    title: "乡试落榜幕僚",
    rank: "民间智囊",
    keywords: "不甘,谋划,嘴碎,翻身",
    shortText: "你前世没考上编制，但把考上的人指挥得团团转。今生别迷信头衔，你靠脑子吃饭。",
    shareText:
      "你朋友测出了「乡试落榜幕僚」\n没考上编制，但指挥上榜的人团团转。\n你会是什么前世身份？",
  },
  {
    id: "P09",
    camp: "power",
    rarity: "rare",
    title: "太庙值夜司仪",
    rank: "祖宗规矩守门人",
    keywords: "仪式感,责任,旧账,稳定",
    shortText: "你前世负责让大人物别在祖宗面前翻车。今生有种奇怪的端庄感，骂人都像写奏折。",
    shareText: "你朋友测出了「太庙值夜司仪」\n让大人物别在祖宗面前翻车。\n你会是什么前世身份？",
  },
  {
    id: "P10",
    camp: "power",
    rarity: "epic",
    title: "废太子身边谋士",
    rank: "失败项目军师",
    keywords: "忠诚,遗憾,复盘,翻盘",
    shortText: "你前世押过一把大的，输了，但没白输。今生你的复盘能力，是从前世血亏里练出来的。",
    shareText: "你朋友测出了「废太子身边谋士」\n押过大注，输了但没白输。\n你会是什么前世身份？",
  },
  {
    id: "P11",
    camp: "power",
    rarity: "normal",
    title: "驿站八卦监察员",
    rank: "基层消息网",
    keywords: "人脉,八卦,敏感,跑动",
    shortText: "你前世靠听墙角掌握半个天下。今生不是爱八卦，是信息雷达没关。",
    shareText: "你朋友测出了「驿站八卦监察员」\n靠听墙角掌握半个天下。\n你会是什么前世身份？",
  },
  {
    id: "P12",
    camp: "power",
    rarity: "legendary",
    title: "九重天命册执笔人",
    rank: "天命档案管理员",
    keywords: "权柄,审判,命簿,隐藏大佬",
    shortText: "你前世不是被写进命簿的人，是改别人批注的人。今生最该学会的，是别把笔交给别人。",
    shareText:
      "你朋友测出了「九重天命册执笔人」\n不是被写进命簿的人，是改批注的人。\n你会是什么前世身份？",
  },
  // Wealth 12
  {
    id: "W01",
    camp: "wealth",
    rarity: "epic",
    title: "破产王府账房先生",
    rank: "贵族财务总监",
    keywords: "算账,止损,嘴硬,理财",
    shortText: "你前世不是穷，是替一整个王府堵窟窿。今生你对钱敏感，是因为灵魂见过现金流断裂。",
    shareText: "你朋友测出了「破产王府账房先生」\n替一整个王府堵窟窿的人。\n你会是什么前世身份？",
  },
  {
    id: "W02",
    camp: "wealth",
    rarity: "rare",
    title: "财神庙临时工",
    rank: "香火现金流管理员",
    keywords: "财感,机会,现实,抠门",
    shortText: "你前世离财神只有半步，可惜是临时合同。今生赚钱靠嗅觉，但别总替别人免费开光。",
    shareText: "你朋友测出了「财神庙临时工」\n离财神只有半步，可惜临时合同。\n你会是什么前世身份？",
  },
  {
    id: "W03",
    camp: "wealth",
    rarity: "normal",
    title: "江南米铺少东家",
    rank: "低调富二代预备役",
    keywords: "稳健,囤货,安全感,慢热",
    shortText: "你前世最懂米价涨跌，今生最怕账户见底。你不是没野心，只是讨厌没准备的冒险。",
    shareText: "你朋友测出了「江南米铺少东家」\n最懂米价涨跌，最怕账户见底。\n你会是什么前世身份？",
  },
  {
    id: "W04",
    camp: "wealth",
    rarity: "epic",
    title: "夜市暴富摊主",
    rank: "高风险现金王",
    keywords: "胆大,欲望,爆发,翻车边缘",
    shortText: "你前世靠一张嘴把夜市卖成商圈。今生能赚快钱，但命盘提醒你：贪快可以，别贪到失控。",
    shareText: "你朋友测出了「夜市暴富摊主」\n靠一张嘴把夜市卖成商圈的人。\n你会是什么前世身份？",
  },
  {
    id: "W05",
    camp: "wealth",
    rarity: "rare",
    title: "茶楼说书收账人",
    rank: "嘴上变现专家",
    keywords: "口才,成交,暗账,人情",
    shortText: "你前世靠讲故事收钱，今生也别低估表达的价格。你一开口，就有人愿意买单。",
    shareText:
      "你朋友测出了「茶楼说书收账人」\n靠讲故事收钱，开口就有人买单。\n你会是什么前世身份？",
  },
  {
    id: "W06",
    camp: "wealth",
    rarity: "normal",
    title: "祖宅钥匙保管员",
    rank: "家产守门人",
    keywords: "房产,安全,旧物,固执",
    shortText: "你前世守着一串钥匙，今生对房子、存款、稳定格外敏感。安全感不是矫情，是命盘底色。",
    shareText:
      "你朋友测出了「祖宅钥匙保管员」\n守着钥匙，对房子存款格外敏感。\n你会是什么前世身份？",
  },
  {
    id: "W07",
    camp: "wealth",
    rarity: "legendary",
    title: "盐铁司暗线商官",
    rank: "国家级搞钱高手",
    keywords: "资源,垄断,布局,权钱",
    shortText: "你前世碰的不是小买卖，是资源盘。今生别只盯工资，你适合做渠道、平台和分成。",
    shareText: "你朋友测出了「盐铁司暗线商官」\n碰的不是小买卖，是资源盘。\n你会是什么前世身份？",
  },
  {
    id: "W08",
    camp: "wealth",
    rarity: "rare",
    title: "西域倒货行商",
    rank: "跨境机会猎人",
    keywords: "流动,差价,冒险,眼光",
    shortText: "你前世靠路上的信息差发财。今生机会常在外地、外圈、外平台，不在原地内耗。",
    shareText: "你朋友测出了「西域倒货行商」\n靠路上的信息差发财。\n你会是什么前世身份？",
  },
  {
    id: "W09",
    camp: "wealth",
    rarity: "normal",
    title: "香料铺慢富掌柜",
    rank: "舒适型生意人",
    keywords: "审美,慢钱,耐心,生活感",
    shortText: "你前世靠香味赚慢钱，今生也不适合硬卷。你越把生活做成风格，越容易变现。",
    shareText: "你朋友测出了「香料铺慢富掌柜」\n靠香味赚慢钱，不适合硬卷。\n你会是什么前世身份？",
  },
  {
    id: "W10",
    camp: "wealth",
    rarity: "epic",
    title: "赌坊风险控制官",
    rank: "反向风控高手",
    keywords: "破局,风险,止损,胆魄",
    shortText: "你前世不是赌徒，是看赌徒怎么输的人。今生只要学会止损，你的胆子就是资产。",
    shareText:
      "你朋友测出了「赌坊风险控制官」\n不是赌徒，是看赌徒怎么输的人。\n你会是什么前世身份？",
  },
  {
    id: "W11",
    camp: "wealth",
    rarity: "rare",
    title: "镖局银库押运官",
    rank: "硬核现金守卫",
    keywords: "纪律,现金,守财,可靠",
    shortText: "你前世押的是银子，今生押的是信用。别人靠热情，你靠可靠赚钱。",
    shareText: "你朋友测出了「镖局银库押运官」\n押的是银子，押的是信用。\n你会是什么前世身份？",
  },
  {
    id: "W12",
    camp: "wealth",
    rarity: "legendary",
    title: "地下钱庄白手套",
    rank: "隐形资本玩家",
    keywords: "隐忍,资源,杠杆,暗线",
    shortText: "你前世的名字不在账本上，但钱都从你手里过。今生要学会用规则赚钱，而不是被规则收费。",
    shareText:
      "你朋友测出了「地下钱庄白手套」\n名字不在账本上，钱都从手里过。\n你会是什么前世身份？",
  },
  // Love 12
  {
    id: "L01",
    camp: "love",
    rarity: "epic",
    title: "桃花司离职红娘",
    rank: "感情系统叛逃者",
    keywords: "桃花,撮合,清醒,嘴欠",
    shortText: "你前世专门给别人牵红线，最后自己被线缠住。今生你不是恋爱脑，是太会看见人心漏洞。",
    shareText: "你朋友测出了「桃花司离职红娘」\n给别人牵红线，自己被线缠住。\n你会是什么前世身份？",
  },
  {
    id: "L02",
    camp: "love",
    rarity: "rare",
    title: "月下信件代写人",
    rank: "古早情绪文案师",
    keywords: "敏感,文艺,暧昧,共情",
    shortText: "你前世替别人写情书，今生替自己想太多。你不是作，是灵魂自带长篇内心戏。",
    shareText: "你朋友测出了「月下信件代写人」\n替别人写情书，替自己想太多。\n你会是什么前世身份？",
  },
  {
    id: "L03",
    camp: "love",
    rarity: "normal",
    title: "宫墙外卖花少女",
    rank: "温柔小生意人",
    keywords: "柔软,慢热,人缘,期待",
    shortText: "你前世靠一篮花混进了很多故事。今生你的温柔是门票，但别把门票送给不进场的人。",
    shareText: "你朋友测出了「宫墙外卖花少女」\n靠一篮花混进很多故事。\n你会是什么前世身份？",
  },
  {
    id: "L04",
    camp: "love",
    rarity: "epic",
    title: "风月楼情报头牌",
    rank: "人心读取器",
    keywords: "魅力,危险,试探,边界",
    shortText: "你前世见过太多真心和假话，所以今生一眼能分辨敷衍。你的桃花不是少，是质量要筛。",
    shareText:
      "你朋友测出了「风月楼情报头牌」\n见过太多真心假话，一眼分辨敷衍。\n你会是什么前世身份？",
  },
  {
    id: "L05",
    camp: "love",
    rarity: "rare",
    title: "和离文书代办师",
    rank: "感情止损顾问",
    keywords: "嘴硬,分寸,谈判,清醒",
    shortText: "你前世帮人写和离书，今生最懂感情里的账。你不是冷血，你只是讨厌无效拉扯。",
    shareText:
      "你朋友测出了「和离文书代办师」\n帮人写和离书，最懂感情里的账。\n你会是什么前世身份？",
  },
  {
    id: "L06",
    camp: "love",
    rarity: "normal",
    title: "相府联姻协调官",
    rank: "体面关系维护者",
    keywords: "体面,责任,顾全,委屈",
    shortText: "你前世维护的是家族体面，今生容易替关系兜底。命盘提醒：体面不能只靠你一个人撑。",
    shareText:
      "你朋友测出了「相府联姻协调官」\n维护家族体面，容易替关系兜底。\n你会是什么前世身份？",
  },
  {
    id: "L07",
    camp: "love",
    rarity: "legendary",
    title: "人间姻缘错题本保管员",
    rank: "高级情感命题官",
    keywords: "吸引,复盘,缘分,洞察",
    shortText: "你前世管的不是姻缘，是姻缘里的错题。今生每段关系都来教你升级审美。",
    shareText:
      "你朋友测出了「人间姻缘错题本保管员」\n管姻缘里的错题，每段关系都来升级审美。\n你会是什么前世身份？",
  },
  {
    id: "L08",
    camp: "love",
    rarity: "rare",
    title: "双生月老助理",
    rank: "关系平衡师",
    keywords: "互补,照顾,拉扯,选择",
    shortText: "你前世专门处理一个热一个冷的姻缘。今生你总在爱与自由之间找平衡。",
    shareText: "你朋友测出了「双生月老助理」\n专门处理一冷一热的姻缘。\n你会是什么前世身份？",
  },
  {
    id: "L09",
    camp: "love",
    rarity: "normal",
    title: "寺庙许愿签管理员",
    rank: "慢热愿望守门人",
    keywords: "慢热,期待,自尊,等待",
    shortText: "你前世看过太多人许愿，今生终于轮到你别乱许。想要什么，要先说清楚。",
    shareText:
      "你朋友测出了「寺庙许愿签管理员」\n看过太多人许愿，轮到你别乱许。\n你会是什么前世身份？",
  },
  {
    id: "L10",
    camp: "love",
    rarity: "epic",
    title: "江湖逃婚少主",
    rank: "自由恋爱反骨仔",
    keywords: "自由,冲动,反骨,重启",
    shortText: "你前世逃过一场不合适的婚，今生也别为了安全感委屈自由。",
    shareText:
      "你朋友测出了「江湖逃婚少主」\n逃过不合适的婚，别为安全感委屈自由。\n你会是什么前世身份？",
  },
  {
    id: "L11",
    camp: "love",
    rarity: "rare",
    title: "长安匿名情诗作者",
    rank: "文字桃花制造机",
    keywords: "表达,暧昧,审美,心动",
    shortText: "你前世写的诗让别人私奔，今生一句话也能让人想多。你的文字比你本人更会撩。",
    shareText:
      "你朋友测出了「长安匿名情诗作者」\n写的诗让别人私奔，文字比本人更会撩。\n你会是什么前世身份？",
  },
  {
    id: "L12",
    camp: "love",
    rarity: "legendary",
    title: "天庭桃花预算审批官",
    rank: "高阶缘分分配员",
    keywords: "魅力,筛选,人气,选择权",
    shortText: "你前世不是缺桃花，是给桃花批预算。今生最重要的不是被爱，是别乱批给不配的人。",
    shareText:
      "你朋友测出了「天庭桃花预算审批官」\n给桃花批预算，别批给不配的人。\n你会是什么前世身份？",
  },
  // Jianghu 12
  {
    id: "J01",
    camp: "jianghu",
    rarity: "legendary",
    title: "边塞失眠军师",
    rank: "战时决策核心",
    keywords: "孤勇,决断,压力,翻盘",
    shortText: "你前世不是将军，却决定将军能不能活。今生压力越大，你越容易开窍。",
    shareText: "你朋友测出了「边塞失眠军师」\n不是将军，决定将军能不能活。\n你会是什么前世身份？",
  },
  {
    id: "J02",
    camp: "jianghu",
    rarity: "epic",
    title: "杀破狼流浪队长",
    rank: "乱世行动派",
    keywords: "破局,行动,反骨,不服",
    shortText: "你前世一生都在换地图，今生也不适合困在一个烂剧本里。你的人生靠破局，不靠忍耐。",
    shareText:
      "你朋友测出了「杀破狼流浪队长」\n一生都在换地图，靠破局不靠忍耐。\n你会是什么前世身份？",
  },
  {
    id: "J03",
    camp: "jianghu",
    rarity: "rare",
    title: "镖局临时背锅侠",
    rank: "危机物流人",
    keywords: "奔波,义气,背锅,执行",
    shortText: "你前世押镖押到怀疑人生，今生也常被迫救场。别怕，你越动越有机会。",
    shareText:
      "你朋友测出了「镖局临时背锅侠」\n押镖押到怀疑人生，越动越有机会。\n你会是什么前世身份？",
  },
  {
    id: "J04",
    camp: "jianghu",
    rarity: "normal",
    title: "山寨二当家助理",
    rank: "草根执行官",
    keywords: "实际,兄弟,野路子,求生",
    shortText: "你前世没有编制，但有江湖地位。今生你最讨厌假正经，因为你见过真江湖。",
    shareText: "你朋友测出了「山寨二当家助理」\n没有编制，但有江湖地位。\n你会是什么前世身份？",
  },
  {
    id: "J05",
    camp: "jianghu",
    rarity: "epic",
    title: "铁匠铺兵器质检员",
    rank: "硬核武器专家",
    keywords: "标准,强硬,实干,挑剔",
    shortText: "你前世专门试刀，今生专门试人。合不合格，你心里有数。",
    shareText: "你朋友测出了「铁匠铺兵器质检员」\n专门试刀，专门试人。\n你会是什么前世身份？",
  },
  {
    id: "J06",
    camp: "jianghu",
    rarity: "rare",
    title: "边城酒馆消息贩子",
    rank: "江湖情报商",
    keywords: "流动,见识,消息,混圈",
    shortText: "你前世知道谁要动手，也知道谁会先跑。今生你适合混圈层，不适合困在小格子。",
    shareText: "你朋友测出了「边城酒馆消息贩子」\n知道谁要动手，谁要先跑。\n你会是什么前世身份？",
  },
  {
    id: "J07",
    camp: "jianghu",
    rarity: "normal",
    title: "码头帮派记账员",
    rank: "社群后勤王",
    keywords: "义气,算账,组织,吐槽",
    shortText: "你前世在码头管账，见过最真实的人情。今生别小看社群，钱和机会都在人里。",
    shareText:
      "你朋友测出了「码头帮派记账员」\n在码头管账，见过最真实的人情。\n你会是什么前世身份？",
  },
  {
    id: "J08",
    camp: "jianghu",
    rarity: "epic",
    title: "密牢审讯记录官",
    rank: "黑暗真相记录者",
    keywords: "锋利,底线,洞察,硬气",
    shortText: "你前世听过太多假话，今生对虚伪过敏。你的毒舌，是灵魂的验钞机。",
    shareText: "你朋友测出了「密牢审讯记录官」\n听过太多假话，对虚伪过敏。\n你会是什么前世身份？",
  },
  {
    id: "J09",
    camp: "jianghu",
    rarity: "rare",
    title: "机关城维修师",
    rank: "危险技术工",
    keywords: "机巧,修复,失眠,脑洞",
    shortText: "你前世修的是机关，今生修的是人生bug。别人看热闹，你看结构。",
    shareText: "你朋友测出了「机关城维修师」\n修的是机关，修的是人生bug。\n你会是什么前世身份？",
  },
  {
    id: "J10",
    camp: "jianghu",
    rarity: "normal",
    title: "流放路上带路人",
    rank: "逆境导航员",
    keywords: "适应,跑路,方向,经验",
    shortText: "你前世最熟的不是家，是路。今生一旦环境不对，换地方比硬熬更旺你。",
    shareText: "你朋友测出了「流放路上带路人」\n最熟的不是家，是路。\n你会是什么前世身份？",
  },
  {
    id: "J11",
    camp: "jianghu",
    rarity: "epic",
    title: "烟火作坊爆改师",
    rank: "爆发型创造者",
    keywords: "冲劲,危险,创意,失控",
    shortText: "你前世把烟火做成了武器。今生灵感很猛，但要学会别把自己也点着。",
    shareText: "你朋友测出了「烟火作坊爆改师」\n把烟火做成武器，灵感很猛。\n你会是什么前世身份？",
  },
  {
    id: "J12",
    camp: "jianghu",
    rarity: "legendary",
    title: "亡国后最后一位护卫",
    rank: "孤胆守局者",
    keywords: "忠诚,孤勇,守护,残局",
    shortText: "你前世守到最后一刻，今生也总不肯轻易放弃。命盘说：忠诚要给值得的人。",
    shareText:
      "你朋友测出了「亡国后最后一位护卫」\n守到最后一刻，忠诚要给值得的人。\n你会是什么前世身份？",
  },
  // Immortal 12
  {
    id: "I01",
    camp: "immortal",
    rarity: "legendary",
    title: "天机阁失眠推演师",
    rank: "命运算法师",
    keywords: "推演,失眠,聪明,过载",
    shortText: "你前世负责算别人三步后的坑，今生脑子也停不下来。你不是焦虑，是天机开太多标签页。",
    shareText:
      "你朋友测出了「天机阁失眠推演师」\n算别人三步后的坑，脑子停不下来。\n你会是什么前世身份？",
  },
  {
    id: "I02",
    camp: "immortal",
    rarity: "epic",
    title: "仙门戒律修订员",
    rank: "规则解释权持有者",
    keywords: "原则,保护,说教,清醒",
    shortText: "你前世改过门规，今生最烦双标。你适合做保护别人边界的人，也要先保护自己。",
    shareText: "你朋友测出了「仙门戒律修订员」\n改过门规，最烦双标。\n你会是什么前世身份？",
  },
  {
    id: "I03",
    camp: "immortal",
    rarity: "rare",
    title: "云梦泽摸鱼散仙",
    rank: "精神疗愈懒人",
    keywords: "松弛,享受,逃班,治愈",
    shortText: "你前世修仙修到学会摸鱼。今生不是没上进心，是灵魂知道过劳会掉功德。",
    shareText:
      "你朋友测出了「云梦泽摸鱼散仙」\n修仙修到学会摸鱼，灵魂知道过劳会掉功德。\n你会是什么前世身份？",
  },
  {
    id: "I04",
    camp: "immortal",
    rarity: "normal",
    title: "藏书阁夜班管理员",
    rank: "知识库守护者",
    keywords: "学习,整理,孤独,文气",
    shortText: "你前世管书，今生管脑内文件夹。你不是想太多，是资料库太大。",
    shareText: "你朋友测出了「藏书阁夜班管理员」\n管书，管脑内文件夹。\n你会是什么前世身份？",
  },
  {
    id: "I05",
    camp: "immortal",
    rarity: "epic",
    title: "辩经大会杠精冠军",
    rank: "逻辑输出机器",
    keywords: "辩论,挑刺,聪明,嘴硬",
    shortText: "你前世靠辩经把师兄弟说自闭。今生要记住：会说是天赋，少说是修行。",
    shareText: "你朋友测出了「辩经大会杠精冠军」\n靠辩经把师兄弟说自闭。\n你会是什么前世身份？",
  },
  {
    id: "I06",
    camp: "immortal",
    rarity: "rare",
    title: "日宫外派巡查员",
    rank: "公开场合发光者",
    keywords: "热心,曝光,责任,能量",
    shortText: "你前世在日宫出差，今生只要站到台前就容易被看见。别再把自己藏成背景板。",
    shareText: "你朋友测出了「日宫外派巡查员」\n在日宫出差，站台前就被看见。\n你会是什么前世身份？",
  },
  {
    id: "I07",
    camp: "immortal",
    rarity: "normal",
    title: "月宫账本修补匠",
    rank: "情绪细节专家",
    keywords: "细腻,审美,存钱,敏感",
    shortText: "你前世给月亮补账，今生给所有人的情绪找漏洞。你敏感，但不是脆弱。",
    shareText:
      "你朋友测出了「月宫账本修补匠」\n给月亮补账，给所有人的情绪找漏洞。\n你会是什么前世身份？",
  },
  {
    id: "I08",
    camp: "immortal",
    rarity: "epic",
    title: "观星台数据分析师",
    rank: "古代大数据命理师",
    keywords: "分析,预判,趋势,熬夜",
    shortText: "你前世靠星象做数据建模，今生看趋势比看热闹准。别浪费你的预判力。",
    shareText:
      "你朋友测出了「观星台数据分析师」\n靠星象做数据建模，看趋势比看热闹准。\n你会是什么前世身份？",
  },
  {
    id: "I09",
    camp: "immortal",
    rarity: "rare",
    title: "药庐火候看守人",
    rank: "慢性修复师",
    keywords: "耐心,照顾,节奏,疗愈",
    shortText: "你前世守火候，今生最懂事不能急。你适合长期主义，别被短视频命格骗了。",
    shareText: "你朋友测出了「药庐火候看守人」\n守火候，最懂事不能急。\n你会是什么前世身份？",
  },
  {
    id: "I10",
    camp: "immortal",
    rarity: "normal",
    title: "洞府门口扫地童子",
    rank: "低调观察员",
    keywords: "观察,低调,心软,隐藏",
    shortText: "你前世看起来扫地，实际听完了所有秘密。今生你不抢戏，但总能看透戏。",
    shareText:
      "你朋友测出了「洞府门口扫地童子」\n看起来扫地，实际听完了所有秘密。\n你会是什么前世身份？",
  },
  {
    id: "I11",
    camp: "immortal",
    rarity: "epic",
    title: "天劫预警播报员",
    rank: "灾前焦虑专家",
    keywords: "预警,焦虑,洞察,过载",
    shortText: "你前世负责提前喊危险，今生也总比别人先慌。别讨厌这点，练好了就是风险管理。",
    shareText:
      "你朋友测出了「天劫预警播报员」\n负责提前喊危险，练好了就是风险管理。\n你会是什么前世身份？",
  },
  {
    id: "I12",
    camp: "immortal",
    rarity: "legendary",
    title: "三清殿梦境审稿人",
    rank: "潜意识编辑官",
    keywords: "梦感,灵性,修正,洞察",
    shortText: "你前世审的不是文章，是梦。今生直觉很准，只是经常被理性骂成想多。",
    shareText:
      "你朋友测出了「三清殿梦境审稿人」\n审的不是文章是梦，直觉很准。\n你会是什么前世身份？",
  },
  // Underworld 12
  {
    id: "U01",
    camp: "underworld",
    rarity: "legendary",
    title: "阴间 HR 判官",
    rank: "地府中层人事",
    keywords: "识人,毒舌,筛选,晚成",
    shortText: "你前世负责筛人，今生负责看穿人。别人还在讲感觉，你已经把底牌翻了三遍。",
    shareText: "你朋友测出了「阴间 HR 判官」\n负责筛人，负责看穿人。\n你会是什么前世身份？",
  },
  {
    id: "U02",
    camp: "underworld",
    rarity: "epic",
    title: "奈何桥排队管理员",
    rank: "轮回秩序维护员",
    keywords: "边界,秩序,冷静,吐槽",
    shortText: "你前世管过太多不肯放下的人。今生你最该学会的是：不值得的人，不用反复送桥票。",
    shareText: "你朋友测出了「奈何桥排队管理员」\n管过太多不肯放下的人。\n你会是什么前世身份？",
  },
  {
    id: "U03",
    camp: "underworld",
    rarity: "rare",
    title: "孟婆汤口味研发员",
    rank: "情绪清除专家",
    keywords: "遗忘,情绪,旧情,治愈",
    shortText: "你前世研究怎么让人忘掉，今生却最容易记住。命盘说：该忘的，不是你，是旧身份。",
    shareText:
      "你朋友测出了「孟婆汤口味研发员」\n研究怎么让人忘掉，自己却最容易记住。\n你会是什么前世身份？",
  },
  {
    id: "U04",
    camp: "underworld",
    rarity: "normal",
    title: "阴司投诉窗口接待",
    rank: "负能量客服",
    keywords: "嘴稳,耐骂,洞察,疲惫",
    shortText: "你前世听了一堆离谱申诉，今生对情绪垃圾格外免疫。你不是冷漠，是客服干久了。",
    shareText:
      "你朋友测出了「阴司投诉窗口接待」\n听了一堆离谱申诉，对情绪垃圾格外免疫。\n你会是什么前世身份？",
  },
  {
    id: "U05",
    camp: "underworld",
    rarity: "epic",
    title: "十八层绩效监察官",
    rank: "阴间风控主管",
    keywords: "狠准,规则,审判,执行",
    shortText: "你前世管的 KPI 是孽力值。今生你看人犯错会沉默，因为你已经在心里扣完分了。",
    shareText:
      "你朋友测出了「十八层绩效监察官」\n管的 KPI 是孽力值，已经在心里扣完分。\n你会是什么前世身份？",
  },
  {
    id: "U06",
    camp: "underworld",
    rarity: "rare",
    title: "前世欠条销毁员",
    rank: "旧账终结者",
    keywords: "债务,止损,算账,清零",
    shortText: "你前世专门销毁还不清的账。今生记住：人情债也有止损线。",
    shareText:
      "你朋友测出了「前世欠条销毁员」\n专门销毁还不清的账，人情债也有止损线。\n你会是什么前世身份？",
  },
  {
    id: "U07",
    camp: "underworld",
    rarity: "normal",
    title: "姻缘债务催收员",
    rank: "感情旧账清算人",
    keywords: "旧情,拉扯,清醒,断舍",
    shortText: "你前世催的是情债，今生别再替别人延期。感情不是贷款，不还就收回。",
    shareText: "你朋友测出了「姻缘债务催收员」\n催的是情债，感情不是贷款。\n你会是什么前世身份？",
  },
  {
    id: "U08",
    camp: "underworld",
    rarity: "epic",
    title: "黄泉路导航员",
    rank: "人生岔路指路人",
    keywords: "方向,转折,告别,清醒",
    shortText: "你前世专门给迷路的魂指路。今生你也总在关键岔口醒得比别人早。",
    shareText: "你朋友测出了「黄泉路导航员」\n专门给迷路的魂指路。\n你会是什么前世身份？",
  },
  {
    id: "U09",
    camp: "underworld",
    rarity: "rare",
    title: "祖坟风水临时修补师",
    rank: "家族旧账维修工",
    keywords: "家族,责任,修补,边界",
    shortText: "你前世修的是风水，今生修的是家里那些说不清的旧账。别全背，你不是祖传万能胶。",
    shareText:
      "你朋友测出了「祖坟风水临时修补师」\n修的是风水，修的是家族旧账。\n你会是什么前世身份？",
  },
  {
    id: "U10",
    camp: "underworld",
    rarity: "normal",
    title: "夜游神打卡员",
    rank: "阴间夜班人",
    keywords: "熬夜,敏感,夜思,观察",
    shortText: "你前世上夜班，今生半夜脑子还在巡逻。别硬熬，夜深不是天机，是睡眠不足。",
    shareText: "你朋友测出了「夜游神打卡员」\n上夜班，半夜脑子还在巡逻。\n你会是什么前世身份？",
  },
  {
    id: "U11",
    camp: "underworld",
    rarity: "epic",
    title: "功过簿复核员",
    rank: "灵魂审计师",
    keywords: "复盘,审计,清算,翻案",
    shortText: "你前世负责给灵魂复核绩效，今生也总爱复盘自己。别太狠，你不是只有错题。",
    shareText: "你朋友测出了「功过簿复核员」\n给灵魂复核绩效，总爱复盘自己。\n你会是什么前世身份？",
  },
  {
    id: "U12",
    camp: "underworld",
    rarity: "legendary",
    title: "忘川边最后一任摆渡人",
    rank: "轮回终局运营官",
    keywords: "告别,洞察,重生,大局",
    shortText: "你前世送走了太多故事，今生才这么怕浪费真心。你不是悲观，你只是知道什么该过河。",
    shareText:
      "你朋友测出了「忘川边最后一任摆渡人」\n送走了太多故事，知道什么该过河。\n你会是什么前世身份？",
  },
];

export const PAST_LIFE_PRESETS: PastLifePreset[] = PRESETS_RAW.map((p) => ({
  id: p.id,
  camp: p.camp,
  rarity: p.rarity,
  title: p.title,
  rank: p.rank,
  keywords: p.keywords.split(",").map((k) => k.trim()),
  triggerHint: p.id,
  shortText: p.shortText,
  shareText: p.shareText,
}));

export function getPresetsByCamp(camp: PastLifeCamp): PastLifePreset[] {
  return PAST_LIFE_PRESETS.filter((p) => p.camp === camp);
}
