import type { AssetManifest } from "./asset-types";

export const assetManifest = {
  "master.trainee.01": {
    id: "master.trainee.01",
    kind: "master",
    rarity: "trainee",
    name: "命由天瞳",
    specialty: "紫微斗数 / 八字 / 每日问事",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-trainee-01-thumb-240.1b29a918ae.webp",
        width: 240,
        height: 360,
        bytes: 17504,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-trainee-01-list-320.8d1346a0d0.webp",
        width: 320,
        height: 480,
        bytes: 30680,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-trainee-01-card-720.860c003807.webp",
        width: 720,
        height: 1080,
        bytes: 85596,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-trainee-01-full-1024.2578996585.webp",
        width: 1024,
        height: 1536,
        bytes: 170908,
        format: "webp",
      },
    },
  },
  "master_avatar.trainee.01": {
    id: "master_avatar.trainee.01",
    kind: "master_avatar",
    rarity: "trainee",
    name: "命由天瞳头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/assets/critical/master_avatar/master-avatar-trainee-01-avatar_sm-64.cae12fa8aa.webp",
        width: 64,
        height: 64,
        bytes: 950,
        format: "webp",
      },
      avatar_md: {
        url: "/assets/critical/master_avatar/master-avatar-trainee-01-avatar_md-96.a35f09a3d8.webp",
        width: 96,
        height: 96,
        bytes: 1890,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-trainee-01-avatar_lg-192.8ec6168ab7.webp",
        width: 192,
        height: 192,
        bytes: 6588,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-trainee-01-raw-512.ff92d08450.webp",
        width: 512,
        height: 512,
        bytes: 31162,
        format: "webp",
      },
    },
  },
  "master.renji.01": {
    id: "master.renji.01",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 灵签童子",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-01-thumb-240.4f25c437a8.webp",
        width: 240,
        height: 360,
        bytes: 22346,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-01-list-320.020ce1dbbe.webp",
        width: 320,
        height: 480,
        bytes: 38666,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-01-card-720.f1d706b9dc.webp",
        width: 720,
        height: 1080,
        bytes: 119538,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-01-full-1024.f007fa239f.webp",
        width: 1024,
        height: 1536,
        bytes: 242052,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.01": {
    id: "master_avatar.renji.01",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 灵签童子头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-01-avatar_sm-64.acffb2bebd.webp",
        width: 64,
        height: 64,
        bytes: 1238,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-01-avatar_md-96.4800b13c13.webp",
        width: 96,
        height: 96,
        bytes: 2604,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-01-avatar_lg-192.4157c9e1fc.webp",
        width: 192,
        height: 192,
        bytes: 10352,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-01-raw-512.1477171ff4.webp",
        width: 512,
        height: 512,
        bytes: 47158,
        format: "webp",
      },
    },
  },
  "master.renji.02": {
    id: "master.renji.02",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 星座塔罗",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-02-thumb-240.4d6e260e72.webp",
        width: 240,
        height: 360,
        bytes: 21534,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-02-list-320.e3db8c610d.webp",
        width: 320,
        height: 480,
        bytes: 38578,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-02-card-720.46746ab355.webp",
        width: 720,
        height: 1080,
        bytes: 114070,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-02-full-1024.42061df14a.webp",
        width: 1024,
        height: 1536,
        bytes: 232356,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.02": {
    id: "master_avatar.renji.02",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 星座塔罗头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-02-avatar_sm-64.8792edfda4.webp",
        width: 64,
        height: 64,
        bytes: 1220,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-02-avatar_md-96.35f588940f.webp",
        width: 96,
        height: 96,
        bytes: 2446,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-02-avatar_lg-192.610855564d.webp",
        width: 192,
        height: 192,
        bytes: 9882,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-02-raw-512.f85ce333c4.webp",
        width: 512,
        height: 512,
        bytes: 43398,
        format: "webp",
      },
    },
  },
  "master.renji.03": {
    id: "master.renji.03",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 流日书记",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-03-thumb-240.7ad6c92608.webp",
        width: 240,
        height: 360,
        bytes: 16926,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-03-list-320.19639bf356.webp",
        width: 320,
        height: 480,
        bytes: 29584,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-03-card-720.0b864b1c94.webp",
        width: 720,
        height: 1080,
        bytes: 84010,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-03-full-1024.4576d0b829.webp",
        width: 1024,
        height: 1536,
        bytes: 178690,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.03": {
    id: "master_avatar.renji.03",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 流日书记头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-03-avatar_sm-64.327a7aae46.webp",
        width: 64,
        height: 64,
        bytes: 882,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-03-avatar_md-96.23bc71aee3.webp",
        width: 96,
        height: 96,
        bytes: 1830,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-03-avatar_lg-192.89b3938396.webp",
        width: 192,
        height: 192,
        bytes: 6826,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-03-raw-512.a6370a23b9.webp",
        width: 512,
        height: 512,
        bytes: 29942,
        format: "webp",
      },
    },
  },
  "master.renji.04": {
    id: "master.renji.04",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 梦占侍者",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-04-thumb-240.3fef9fa24e.webp",
        width: 240,
        height: 360,
        bytes: 19202,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-04-list-320.b4ad3c84d3.webp",
        width: 320,
        height: 480,
        bytes: 33626,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-04-card-720.0b2187032d.webp",
        width: 720,
        height: 1080,
        bytes: 99784,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-04-full-1024.702304e9f1.webp",
        width: 1024,
        height: 1536,
        bytes: 208036,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.04": {
    id: "master_avatar.renji.04",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 梦占侍者头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-04-avatar_sm-64.eaa494c0f9.webp",
        width: 64,
        height: 64,
        bytes: 1100,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-04-avatar_md-96.8fe96a36f1.webp",
        width: 96,
        height: 96,
        bytes: 2206,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-04-avatar_lg-192.4c456f1022.webp",
        width: 192,
        height: 192,
        bytes: 8706,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-04-raw-512.15af8549ed.webp",
        width: 512,
        height: 512,
        bytes: 40120,
        format: "webp",
      },
    },
  },
  "master.renji.05": {
    id: "master.renji.05",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 小六壬客",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-05-thumb-240.3c796018a0.webp",
        width: 240,
        height: 360,
        bytes: 22330,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-05-list-320.0b0248a052.webp",
        width: 320,
        height: 480,
        bytes: 38498,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-05-card-720.be8d9bc339.webp",
        width: 720,
        height: 1080,
        bytes: 119606,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-05-full-1024.99dc475b11.webp",
        width: 1024,
        height: 1536,
        bytes: 243302,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.05": {
    id: "master_avatar.renji.05",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 小六壬客头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-05-avatar_sm-64.eece73884d.webp",
        width: 64,
        height: 64,
        bytes: 1202,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-05-avatar_md-96.6e0dab97d2.webp",
        width: 96,
        height: 96,
        bytes: 2522,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-05-avatar_lg-192.3d98aa6853.webp",
        width: 192,
        height: 192,
        bytes: 9978,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-05-raw-512.45ed34f333.webp",
        width: 512,
        height: 512,
        bytes: 46790,
        format: "webp",
      },
    },
  },
  "master.renji.06": {
    id: "master.renji.06",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 梅花易数",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-06-thumb-240.1721373c4b.webp",
        width: 240,
        height: 360,
        bytes: 21156,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-06-list-320.a74dd07746.webp",
        width: 320,
        height: 480,
        bytes: 36772,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-06-card-720.5ec11bd6d3.webp",
        width: 720,
        height: 1080,
        bytes: 107766,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-06-full-1024.22a2fc3cdd.webp",
        width: 1024,
        height: 1536,
        bytes: 217114,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.06": {
    id: "master_avatar.renji.06",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 梅花易数头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-06-avatar_sm-64.b52e03f198.webp",
        width: 64,
        height: 64,
        bytes: 1130,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-06-avatar_md-96.7f263dfffe.webp",
        width: 96,
        height: 96,
        bytes: 2268,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-06-avatar_lg-192.f039508cb5.webp",
        width: 192,
        height: 192,
        bytes: 9116,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-06-raw-512.9bc54e03eb.webp",
        width: 512,
        height: 512,
        bytes: 40460,
        format: "webp",
      },
    },
  },
  "master.renji.07": {
    id: "master.renji.07",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 签筒守夜",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-07-thumb-240.1ee875d28f.webp",
        width: 240,
        height: 360,
        bytes: 20888,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-07-list-320.735888b1c5.webp",
        width: 320,
        height: 480,
        bytes: 36452,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-07-card-720.f8715f3ed3.webp",
        width: 720,
        height: 1080,
        bytes: 102242,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-07-full-1024.53156f0a35.webp",
        width: 1024,
        height: 1536,
        bytes: 207048,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.07": {
    id: "master_avatar.renji.07",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 签筒守夜头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-07-avatar_sm-64.aa52a355aa.webp",
        width: 64,
        height: 64,
        bytes: 1136,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-07-avatar_md-96.79aa6b1844.webp",
        width: 96,
        height: 96,
        bytes: 2444,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-07-avatar_lg-192.7b2f54559d.webp",
        width: 192,
        height: 192,
        bytes: 9440,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-07-raw-512.dd28fb2995.webp",
        width: 512,
        height: 512,
        bytes: 42342,
        format: "webp",
      },
    },
  },
  "master.renji.08": {
    id: "master.renji.08",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 情缘问卜",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-08-thumb-240.03c7130e31.webp",
        width: 240,
        height: 360,
        bytes: 22882,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-08-list-320.46bf5078e5.webp",
        width: 320,
        height: 480,
        bytes: 40014,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-08-card-720.9ca0e7410c.webp",
        width: 720,
        height: 1080,
        bytes: 125898,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-08-full-1024.c34b698658.webp",
        width: 1024,
        height: 1536,
        bytes: 259596,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.08": {
    id: "master_avatar.renji.08",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 情缘问卜头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-08-avatar_sm-64.dc25e8e91c.webp",
        width: 64,
        height: 64,
        bytes: 1280,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-08-avatar_md-96.62ef89c5de.webp",
        width: 96,
        height: 96,
        bytes: 2630,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-08-avatar_lg-192.58636cf599.webp",
        width: 192,
        height: 192,
        bytes: 10372,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-08-raw-512.f4623281ce.webp",
        width: 512,
        height: 512,
        bytes: 48830,
        format: "webp",
      },
    },
  },
  "master.renji.09": {
    id: "master.renji.09",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 财星巡游",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-09-thumb-240.ce2b7a86ee.webp",
        width: 240,
        height: 360,
        bytes: 21136,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-09-list-320.c536044e6d.webp",
        width: 320,
        height: 480,
        bytes: 37402,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-09-card-720.527bc27471.webp",
        width: 720,
        height: 1080,
        bytes: 118144,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-09-full-1024.c1d2bfb0c4.webp",
        width: 1024,
        height: 1536,
        bytes: 245986,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.09": {
    id: "master_avatar.renji.09",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 财星巡游头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-09-avatar_sm-64.8a70ea496e.webp",
        width: 64,
        height: 64,
        bytes: 1194,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-09-avatar_md-96.01f11561be.webp",
        width: 96,
        height: 96,
        bytes: 2446,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-09-avatar_lg-192.57a3ae3853.webp",
        width: 192,
        height: 192,
        bytes: 10018,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-09-raw-512.5c82426743.webp",
        width: 512,
        height: 512,
        bytes: 48564,
        format: "webp",
      },
    },
  },
  "master.renji.10": {
    id: "master.renji.10",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 八字初判",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-10-thumb-240.945c3f162d.webp",
        width: 240,
        height: 360,
        bytes: 23146,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-10-list-320.902a1d640c.webp",
        width: 320,
        height: 480,
        bytes: 40722,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-10-card-720.6b5e215481.webp",
        width: 720,
        height: 1080,
        bytes: 119626,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-10-full-1024.a6d886f06a.webp",
        width: 1024,
        height: 1536,
        bytes: 241012,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.10": {
    id: "master_avatar.renji.10",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 八字初判头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-10-avatar_sm-64.58cc5e332a.webp",
        width: 64,
        height: 64,
        bytes: 1334,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-10-avatar_md-96.bfc0ae9fe0.webp",
        width: 96,
        height: 96,
        bytes: 2804,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-10-avatar_lg-192.a897df1884.webp",
        width: 192,
        height: 192,
        bytes: 10920,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-10-raw-512.ff79fad26c.webp",
        width: 512,
        height: 512,
        bytes: 51750,
        format: "webp",
      },
    },
  },
  "master.renji.11": {
    id: "master.renji.11",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 紫微灯使",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-11-thumb-240.a18fd75222.webp",
        width: 240,
        height: 360,
        bytes: 27202,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-11-list-320.a699ad9be5.webp",
        width: 320,
        height: 480,
        bytes: 46596,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-11-card-720.a474b441ee.webp",
        width: 720,
        height: 1080,
        bytes: 135770,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-11-full-1024.398e68f078.webp",
        width: 1024,
        height: 1536,
        bytes: 269514,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.11": {
    id: "master_avatar.renji.11",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 紫微灯使头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-11-avatar_sm-64.8300b7c54b.webp",
        width: 64,
        height: 64,
        bytes: 1474,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-11-avatar_md-96.bd9c642619.webp",
        width: 96,
        height: 96,
        bytes: 3128,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-11-avatar_lg-192.316a1ada3f.webp",
        width: 192,
        height: 192,
        bytes: 12460,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-11-raw-512.d6f4e8b38c.webp",
        width: 512,
        height: 512,
        bytes: 58130,
        format: "webp",
      },
    },
  },
  "master.renji.12": {
    id: "master.renji.12",
    kind: "master",
    rarity: "renji",
    name: "人玑命师 · 日课行者",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#3158d4",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-renji-12-thumb-240.e1e6839b9f.webp",
        width: 240,
        height: 360,
        bytes: 26168,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-renji-12-list-320.47c9f0234d.webp",
        width: 320,
        height: 480,
        bytes: 45670,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-renji-12-card-720.1d63b103f4.webp",
        width: 720,
        height: 1080,
        bytes: 144740,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-renji-12-full-1024.689ebfdb4d.webp",
        width: 1024,
        height: 1536,
        bytes: 297162,
        format: "webp",
      },
    },
  },
  "master_avatar.renji.12": {
    id: "master_avatar.renji.12",
    kind: "master_avatar",
    rarity: "renji",
    name: "人玑命师 · 日课行者头像",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-12-avatar_sm-64.e430846756.webp",
        width: 64,
        height: 64,
        bytes: 1544,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-12-avatar_md-96.87013eea07.webp",
        width: 96,
        height: 96,
        bytes: 3212,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-12-avatar_lg-192.e3562c8928.webp",
        width: 192,
        height: 192,
        bytes: 12596,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-renji-12-raw-512.5104d28cb5.webp",
        width: 512,
        height: 512,
        bytes: 61708,
        format: "webp",
      },
    },
  },
  "master.dixuan.01": {
    id: "master.dixuan.01",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 合婚画司",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-01-thumb-240.cb57338d7c.webp",
        width: 240,
        height: 360,
        bytes: 28076,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-01-list-320.3ac5aa73f7.webp",
        width: 320,
        height: 480,
        bytes: 47848,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-01-card-720.aa338a27de.webp",
        width: 720,
        height: 1080,
        bytes: 145216,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-01-full-1024.76458ec1d5.webp",
        width: 1024,
        height: 1536,
        bytes: 279852,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.01": {
    id: "master_avatar.dixuan.01",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 合婚画司头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-01-avatar_sm-64.7e25719f3d.webp",
        width: 64,
        height: 64,
        bytes: 1448,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-01-avatar_md-96.aca702c76b.webp",
        width: 96,
        height: 96,
        bytes: 3022,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-01-avatar_lg-192.c99d54fec3.webp",
        width: 192,
        height: 192,
        bytes: 12070,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-01-raw-512.52dc5252e9.webp",
        width: 512,
        height: 512,
        bytes: 55440,
        format: "webp",
      },
    },
  },
  "master.dixuan.02": {
    id: "master.dixuan.02",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 风水择日",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-02-thumb-240.0f0f36e355.webp",
        width: 240,
        height: 360,
        bytes: 28134,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-02-list-320.6fd1ecceeb.webp",
        width: 320,
        height: 480,
        bytes: 48780,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-02-card-720.cba1e9cc0c.webp",
        width: 720,
        height: 1080,
        bytes: 148242,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-02-full-1024.59be16a29e.webp",
        width: 1024,
        height: 1536,
        bytes: 289800,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.02": {
    id: "master_avatar.dixuan.02",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 风水择日头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-02-avatar_sm-64.abd12f146c.webp",
        width: 64,
        height: 64,
        bytes: 1730,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-02-avatar_md-96.36316ecb57.webp",
        width: 96,
        height: 96,
        bytes: 3498,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-02-avatar_lg-192.d0446394fb.webp",
        width: 192,
        height: 192,
        bytes: 13450,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-02-raw-512.7e0ec92b44.webp",
        width: 512,
        height: 512,
        bytes: 64168,
        format: "webp",
      },
    },
  },
  "master.dixuan.03": {
    id: "master.dixuan.03",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 事业星官",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-03-thumb-240.9ad3abcb83.webp",
        width: 240,
        height: 360,
        bytes: 27032,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-03-list-320.b5946a1490.webp",
        width: 320,
        height: 480,
        bytes: 46540,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-03-card-720.f55087ceff.webp",
        width: 720,
        height: 1080,
        bytes: 138170,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-03-full-1024.9e92bbbd3c.webp",
        width: 1024,
        height: 1536,
        bytes: 268844,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.03": {
    id: "master_avatar.dixuan.03",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 事业星官头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-03-avatar_sm-64.951860000f.webp",
        width: 64,
        height: 64,
        bytes: 1438,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-03-avatar_md-96.50b6b3a3fb.webp",
        width: 96,
        height: 96,
        bytes: 2996,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-03-avatar_lg-192.13b537dcf6.webp",
        width: 192,
        height: 192,
        bytes: 12024,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-03-raw-512.c36ae99785.webp",
        width: 512,
        height: 512,
        bytes: 55634,
        format: "webp",
      },
    },
  },
  "master.dixuan.04": {
    id: "master.dixuan.04",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 财帛掌簿",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-04-thumb-240.e807b06518.webp",
        width: 240,
        height: 360,
        bytes: 29356,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-04-list-320.f3473bc527.webp",
        width: 320,
        height: 480,
        bytes: 50116,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-04-card-720.b9260337aa.webp",
        width: 720,
        height: 1080,
        bytes: 143054,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-04-full-1024.6b7e108553.webp",
        width: 1024,
        height: 1536,
        bytes: 274544,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.04": {
    id: "master_avatar.dixuan.04",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 财帛掌簿头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-04-avatar_sm-64.3ec55e5d40.webp",
        width: 64,
        height: 64,
        bytes: 1604,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-04-avatar_md-96.1e297732c1.webp",
        width: 96,
        height: 96,
        bytes: 3318,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-04-avatar_lg-192.48700f9357.webp",
        width: 192,
        height: 192,
        bytes: 13180,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-04-raw-512.6c9233d924.webp",
        width: 512,
        height: 512,
        bytes: 57676,
        format: "webp",
      },
    },
  },
  "master.dixuan.05": {
    id: "master.dixuan.05",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 流年推官",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-05-thumb-240.9a819410e3.webp",
        width: 240,
        height: 360,
        bytes: 27460,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-05-list-320.9e47b34fc7.webp",
        width: 320,
        height: 480,
        bytes: 47556,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-05-card-720.bc21433375.webp",
        width: 720,
        height: 1080,
        bytes: 143264,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-05-full-1024.080b1d9004.webp",
        width: 1024,
        height: 1536,
        bytes: 278660,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.05": {
    id: "master_avatar.dixuan.05",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 流年推官头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-05-avatar_sm-64.0a742a32f6.webp",
        width: 64,
        height: 64,
        bytes: 1366,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-05-avatar_md-96.d122a37797.webp",
        width: 96,
        height: 96,
        bytes: 2912,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-05-avatar_lg-192.7ae801663b.webp",
        width: 192,
        height: 192,
        bytes: 11888,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-05-raw-512.8f02454887.webp",
        width: 512,
        height: 512,
        bytes: 55490,
        format: "webp",
      },
    },
  },
  "master.dixuan.06": {
    id: "master.dixuan.06",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 宅运策士",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-06-thumb-240.edaf988e27.webp",
        width: 240,
        height: 360,
        bytes: 28962,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-06-list-320.0e1a92e4db.webp",
        width: 320,
        height: 480,
        bytes: 50228,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-06-card-720.62a4253e3d.webp",
        width: 720,
        height: 1080,
        bytes: 154222,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-06-full-1024.6d89b8a8e5.webp",
        width: 1024,
        height: 1536,
        bytes: 298856,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.06": {
    id: "master_avatar.dixuan.06",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 宅运策士头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-06-avatar_sm-64.01f2812b12.webp",
        width: 64,
        height: 64,
        bytes: 1574,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-06-avatar_md-96.bbe1dac505.webp",
        width: 96,
        height: 96,
        bytes: 3246,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-06-avatar_lg-192.9679dc2ac2.webp",
        width: 192,
        height: 192,
        bytes: 12730,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-06-raw-512.e42012ae70.webp",
        width: 512,
        height: 512,
        bytes: 59238,
        format: "webp",
      },
    },
  },
  "master.dixuan.07": {
    id: "master.dixuan.07",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 桃花判客",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-07-thumb-240.77ac1f0ff2.webp",
        width: 240,
        height: 360,
        bytes: 26292,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-07-list-320.4a3d187712.webp",
        width: 320,
        height: 480,
        bytes: 45526,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-07-card-720.e1407bc37d.webp",
        width: 720,
        height: 1080,
        bytes: 136922,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-07-full-1024.d6acb975ac.webp",
        width: 1024,
        height: 1536,
        bytes: 267524,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.07": {
    id: "master_avatar.dixuan.07",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 桃花判客头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-07-avatar_sm-64.696707e300.webp",
        width: 64,
        height: 64,
        bytes: 1340,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-07-avatar_md-96.28f4eb4191.webp",
        width: 96,
        height: 96,
        bytes: 2852,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-07-avatar_lg-192.32c8d7e737.webp",
        width: 192,
        height: 192,
        bytes: 11866,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-07-raw-512.fcfb426496.webp",
        width: 512,
        height: 512,
        bytes: 55854,
        format: "webp",
      },
    },
  },
  "master.dixuan.08": {
    id: "master.dixuan.08",
    kind: "master",
    rarity: "dixuan",
    name: "地璇命师 · 奇门隐者",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#6d4bd1",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-dixuan-08-thumb-240.3f4dc8c959.webp",
        width: 240,
        height: 360,
        bytes: 27946,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-dixuan-08-list-320.19a486d912.webp",
        width: 320,
        height: 480,
        bytes: 49446,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-dixuan-08-card-720.b220c7df6b.webp",
        width: 720,
        height: 1080,
        bytes: 155054,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-dixuan-08-full-1024.f844b5dcb8.webp",
        width: 1024,
        height: 1536,
        bytes: 309642,
        format: "webp",
      },
    },
  },
  "master_avatar.dixuan.08": {
    id: "master_avatar.dixuan.08",
    kind: "master_avatar",
    rarity: "dixuan",
    name: "地璇命师 · 奇门隐者头像",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-08-avatar_sm-64.4a9780f7a5.webp",
        width: 64,
        height: 64,
        bytes: 1338,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-08-avatar_md-96.ae60903350.webp",
        width: 96,
        height: 96,
        bytes: 2996,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-08-avatar_lg-192.a282636e91.webp",
        width: 192,
        height: 192,
        bytes: 12644,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-dixuan-08-raw-512.dd9bd3680f.webp",
        width: 512,
        height: 512,
        bytes: 62024,
        format: "webp",
      },
    },
  },
  "master.tianshu.01": {
    id: "master.tianshu.01",
    kind: "master",
    rarity: "tianshu",
    name: "天枢命师 · 北斗执笔",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#d7a94d",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-tianshu-01-thumb-240.0ff812d973.webp",
        width: 240,
        height: 360,
        bytes: 33246,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-tianshu-01-list-320.3a1399a8e9.webp",
        width: 320,
        height: 480,
        bytes: 57536,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-tianshu-01-card-720.798ba88d91.webp",
        width: 720,
        height: 1080,
        bytes: 173028,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-tianshu-01-full-1024.c026f89e38.webp",
        width: 1024,
        height: 1536,
        bytes: 333810,
        format: "webp",
      },
    },
  },
  "master_avatar.tianshu.01": {
    id: "master_avatar.tianshu.01",
    kind: "master_avatar",
    rarity: "tianshu",
    name: "天枢命师 · 北斗执笔头像",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-01-avatar_sm-64.56d01205c9.webp",
        width: 64,
        height: 64,
        bytes: 1990,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-01-avatar_md-96.8ac792079a.webp",
        width: 96,
        height: 96,
        bytes: 4110,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-01-avatar_lg-192.a8842bf4af.webp",
        width: 192,
        height: 192,
        bytes: 15856,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-01-raw-512.f2f9b418ec.webp",
        width: 512,
        height: 512,
        bytes: 72466,
        format: "webp",
      },
    },
  },
  "master.tianshu.02": {
    id: "master.tianshu.02",
    kind: "master",
    rarity: "tianshu",
    name: "天枢命师 · 紫微帝座",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#d7a94d",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-tianshu-02-thumb-240.f677f63cfb.webp",
        width: 240,
        height: 360,
        bytes: 33108,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-tianshu-02-list-320.6e0848763d.webp",
        width: 320,
        height: 480,
        bytes: 57756,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-tianshu-02-card-720.d91165d781.webp",
        width: 720,
        height: 1080,
        bytes: 173236,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-tianshu-02-full-1024.e38a17cb5e.webp",
        width: 1024,
        height: 1536,
        bytes: 333404,
        format: "webp",
      },
    },
  },
  "master_avatar.tianshu.02": {
    id: "master_avatar.tianshu.02",
    kind: "master_avatar",
    rarity: "tianshu",
    name: "天枢命师 · 紫微帝座头像",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-02-avatar_sm-64.4e9611f1bc.webp",
        width: 64,
        height: 64,
        bytes: 1808,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-02-avatar_md-96.f9733e25ea.webp",
        width: 96,
        height: 96,
        bytes: 3752,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-02-avatar_lg-192.8966a8d8d4.webp",
        width: 192,
        height: 192,
        bytes: 14414,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-02-raw-512.d1faad6023.webp",
        width: 512,
        height: 512,
        bytes: 66492,
        format: "webp",
      },
    },
  },
  "master.tianshu.03": {
    id: "master.tianshu.03",
    kind: "master",
    rarity: "tianshu",
    name: "天枢命师 · 天机策令",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#d7a94d",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-tianshu-03-thumb-240.07636c2efb.webp",
        width: 240,
        height: 360,
        bytes: 31998,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-tianshu-03-list-320.8a6622218f.webp",
        width: 320,
        height: 480,
        bytes: 55524,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-tianshu-03-card-720.386bcb867d.webp",
        width: 720,
        height: 1080,
        bytes: 176168,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-tianshu-03-full-1024.dd54ff1c4c.webp",
        width: 1024,
        height: 1536,
        bytes: 339918,
        format: "webp",
      },
    },
  },
  "master_avatar.tianshu.03": {
    id: "master_avatar.tianshu.03",
    kind: "master_avatar",
    rarity: "tianshu",
    name: "天枢命师 · 天机策令头像",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-03-avatar_sm-64.e796a733ab.webp",
        width: 64,
        height: 64,
        bytes: 1820,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-03-avatar_md-96.1e9fe01d58.webp",
        width: 96,
        height: 96,
        bytes: 3796,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-03-avatar_lg-192.e922e870c4.webp",
        width: 192,
        height: 192,
        bytes: 14934,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-03-raw-512.501059c53c.webp",
        width: 512,
        height: 512,
        bytes: 71408,
        format: "webp",
      },
    },
  },
  "master.tianshu.04": {
    id: "master.tianshu.04",
    kind: "master",
    rarity: "tianshu",
    name: "天枢命师 · 金阙司命",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#d7a94d",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-tianshu-04-thumb-240.77437d2634.webp",
        width: 240,
        height: 360,
        bytes: 31148,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-tianshu-04-list-320.c0d0c2e9d7.webp",
        width: 320,
        height: 480,
        bytes: 54598,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-tianshu-04-card-720.78babbcdd2.webp",
        width: 720,
        height: 1080,
        bytes: 169860,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-tianshu-04-full-1024.2f8f18820f.webp",
        width: 1024,
        height: 1536,
        bytes: 336716,
        format: "webp",
      },
    },
  },
  "master_avatar.tianshu.04": {
    id: "master_avatar.tianshu.04",
    kind: "master_avatar",
    rarity: "tianshu",
    name: "天枢命师 · 金阙司命头像",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-04-avatar_sm-64.4cd6ab0da6.webp",
        width: 64,
        height: 64,
        bytes: 1682,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-04-avatar_md-96.c270c3b4d8.webp",
        width: 96,
        height: 96,
        bytes: 3630,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-04-avatar_lg-192.d4ba97ff2c.webp",
        width: 192,
        height: 192,
        bytes: 14630,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-tianshu-04-raw-512.1f37584566.webp",
        width: 512,
        height: 512,
        bytes: 69360,
        format: "webp",
      },
    },
  },
  "master.chaos.01": {
    id: "master.chaos.01",
    kind: "master",
    rarity: "chaos",
    name: "混沌命师 · 鸿蒙未判",
    specialty: "命理推演",
    aspectRatio: 0.6666666666666666,
    dominantColor: "#141018",
    variants: {
      thumb: {
        url: "/api/assets/art/master/master-chaos-01-thumb-240.116bec73af.webp",
        width: 240,
        height: 360,
        bytes: 29506,
        format: "webp",
      },
      list: {
        url: "/api/assets/art/master/master-chaos-01-list-320.60b2a85fc2.webp",
        width: 320,
        height: 480,
        bytes: 50882,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/master/master-chaos-01-card-720.97ecd0e91a.webp",
        width: 720,
        height: 1080,
        bytes: 155002,
        format: "webp",
      },
      full: {
        url: "/api/assets/art/master/master-chaos-01-full-1024.462c4f69bf.webp",
        width: 1024,
        height: 1536,
        bytes: 298220,
        format: "webp",
      },
    },
  },
  "master_avatar.chaos.01": {
    id: "master_avatar.chaos.01",
    kind: "master_avatar",
    rarity: "chaos",
    name: "混沌命师 · 鸿蒙未判头像",
    aspectRatio: 1,
    dominantColor: "#141018",
    variants: {
      avatar_sm: {
        url: "/api/assets/art/master_avatar/master-avatar-chaos-01-avatar_sm-64.091fbc517b.webp",
        width: 64,
        height: 64,
        bytes: 1448,
        format: "webp",
      },
      avatar_md: {
        url: "/api/assets/art/master_avatar/master-avatar-chaos-01-avatar_md-96.412d393802.webp",
        width: 96,
        height: 96,
        bytes: 3060,
        format: "webp",
      },
      avatar_lg: {
        url: "/api/assets/art/master_avatar/master-avatar-chaos-01-avatar_lg-192.7b04174a5f.webp",
        width: 192,
        height: 192,
        bytes: 12424,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/master_avatar/master-avatar-chaos-01-raw-512.011cda585c.webp",
        width: 512,
        height: 512,
        bytes: 63304,
        format: "webp",
      },
    },
  },
  "blind_box.box.standard": {
    id: "blind_box.box.standard",
    kind: "blind_box",
    name: "戏命师盲盒 · standard",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      box: {
        url: "/api/assets/art/blind_box/blind-box-box-standard-box-512.45c44afefd.webp",
        width: 512,
        height: 512,
        bytes: 53782,
        format: "webp",
      },
    },
  },
  "blind_box.box.renji": {
    id: "blind_box.box.renji",
    kind: "blind_box",
    rarity: "renji",
    name: "戏命师盲盒 · renji",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      box: {
        url: "/api/assets/art/blind_box/blind-box-box-renji-box-512.8856044b5e.webp",
        width: 512,
        height: 512,
        bytes: 63492,
        format: "webp",
      },
    },
  },
  "blind_box.box.dixuan": {
    id: "blind_box.box.dixuan",
    kind: "blind_box",
    rarity: "dixuan",
    name: "戏命师盲盒 · dixuan",
    aspectRatio: 1,
    dominantColor: "#6d4bd1",
    variants: {
      box: {
        url: "/api/assets/art/blind_box/blind-box-box-dixuan-box-512.a35e13924e.webp",
        width: 512,
        height: 512,
        bytes: 64390,
        format: "webp",
      },
    },
  },
  "blind_box.box.tianshu": {
    id: "blind_box.box.tianshu",
    kind: "blind_box",
    rarity: "tianshu",
    name: "戏命师盲盒 · tianshu",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      box: {
        url: "/api/assets/art/blind_box/blind-box-box-tianshu-box-512.40bde80d29.webp",
        width: 512,
        height: 512,
        bytes: 70674,
        format: "webp",
      },
    },
  },
  "blind_box.box.chaos": {
    id: "blind_box.box.chaos",
    kind: "blind_box",
    rarity: "chaos",
    name: "戏命师盲盒 · chaos",
    aspectRatio: 1,
    dominantColor: "#141018",
    variants: {
      box: {
        url: "/api/assets/art/blind_box/blind-box-box-chaos-box-512.33e58dbb1a.webp",
        width: 512,
        height: 512,
        bytes: 57704,
        format: "webp",
      },
    },
  },
  "blind_box.frame.01": {
    id: "blind_box.frame.01",
    kind: "blind_box_effect",
    name: "开盒序列帧 01",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-01-frame-512.90898eaa27.webp",
        width: 512,
        height: 512,
        bytes: 27920,
        format: "webp",
      },
    },
  },
  "blind_box.frame.02": {
    id: "blind_box.frame.02",
    kind: "blind_box_effect",
    name: "开盒序列帧 02",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-02-frame-512.e3e0deeb54.webp",
        width: 512,
        height: 512,
        bytes: 40902,
        format: "webp",
      },
    },
  },
  "blind_box.frame.03": {
    id: "blind_box.frame.03",
    kind: "blind_box_effect",
    name: "开盒序列帧 03",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-03-frame-512.a885d1c3a6.webp",
        width: 512,
        height: 512,
        bytes: 49150,
        format: "webp",
      },
    },
  },
  "blind_box.frame.04": {
    id: "blind_box.frame.04",
    kind: "blind_box_effect",
    name: "开盒序列帧 04",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-04-frame-512.fb4e9c05db.webp",
        width: 512,
        height: 512,
        bytes: 66432,
        format: "webp",
      },
    },
  },
  "blind_box.frame.05": {
    id: "blind_box.frame.05",
    kind: "blind_box_effect",
    name: "开盒序列帧 05",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-05-frame-512.f6d97acd1d.webp",
        width: 512,
        height: 512,
        bytes: 50598,
        format: "webp",
      },
    },
  },
  "blind_box.frame.06": {
    id: "blind_box.frame.06",
    kind: "blind_box_effect",
    name: "开盒序列帧 06",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      frame: {
        url: "/api/assets/art/blind_box_effect/blind-box-frame-06-frame-512.a8a17db7aa.webp",
        width: 512,
        height: 512,
        bytes: 30502,
        format: "webp",
      },
    },
  },
  "blind_box.result.renji": {
    id: "blind_box.result.renji",
    kind: "blind_box_result",
    rarity: "renji",
    name: "抽中结果背景 · renji",
    aspectRatio: 0.5625,
    dominantColor: "#3158d4",
    variants: {
      mobile: {
        url: "/api/assets/art/blind_box_result/blind-box-result-renji-mobile-720.aec9ec8078.webp",
        width: 720,
        height: 1280,
        bytes: 160184,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/blind_box_result/blind-box-result-renji-share-1080.e691217518.webp",
        width: 1080,
        height: 1920,
        bytes: 282552,
        format: "webp",
      },
    },
  },
  "blind_box.result.dixuan": {
    id: "blind_box.result.dixuan",
    kind: "blind_box_result",
    rarity: "dixuan",
    name: "抽中结果背景 · dixuan",
    aspectRatio: 0.5625,
    dominantColor: "#6d4bd1",
    variants: {
      mobile: {
        url: "/api/assets/art/blind_box_result/blind-box-result-dixuan-mobile-720.95bc296b0c.webp",
        width: 720,
        height: 1280,
        bytes: 200984,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/blind_box_result/blind-box-result-dixuan-share-1080.f4d51178fe.webp",
        width: 1080,
        height: 1920,
        bytes: 369932,
        format: "webp",
      },
    },
  },
  "blind_box.result.tianshu": {
    id: "blind_box.result.tianshu",
    kind: "blind_box_result",
    rarity: "tianshu",
    name: "抽中结果背景 · tianshu",
    aspectRatio: 0.5625,
    dominantColor: "#d7a94d",
    variants: {
      mobile: {
        url: "/api/assets/art/blind_box_result/blind-box-result-tianshu-mobile-720.70fdcf5253.webp",
        width: 720,
        height: 1280,
        bytes: 166756,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/blind_box_result/blind-box-result-tianshu-share-1080.f69a21d045.webp",
        width: 1080,
        height: 1920,
        bytes: 310386,
        format: "webp",
      },
    },
  },
  "blind_box.result.chaos": {
    id: "blind_box.result.chaos",
    kind: "blind_box_result",
    rarity: "chaos",
    name: "抽中结果背景 · chaos",
    aspectRatio: 0.5625,
    dominantColor: "#141018",
    variants: {
      mobile: {
        url: "/api/assets/art/blind_box_result/blind-box-result-chaos-mobile-720.b733ec46d8.webp",
        width: 720,
        height: 1280,
        bytes: 197202,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/blind_box_result/blind-box-result-chaos-share-1080.cc11c03951.webp",
        width: 1080,
        height: 1920,
        bytes: 348562,
        format: "webp",
      },
    },
  },
  "rune.silver.01": {
    id: "rune.silver.01",
    kind: "rune",
    rarity: "silver",
    name: "角木蛟印",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-01-icon-96.eadf628ccd.webp",
        width: 96,
        height: 96,
        bytes: 2822,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-01-thumb-240.d6dabcceef.webp",
        width: 240,
        height: 360,
        bytes: 25388,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-01-card-720.9ea7f581cd.webp",
        width: 720,
        height: 1080,
        bytes: 110540,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-01-raw-512.50a659378c.webp",
        width: 512,
        height: 512,
        bytes: 43956,
        format: "webp",
      },
    },
  },
  "rune.silver.02": {
    id: "rune.silver.02",
    kind: "rune",
    rarity: "silver",
    name: "心月狐契",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-02-icon-96.f40395064e.webp",
        width: 96,
        height: 96,
        bytes: 2484,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-02-thumb-240.e73334db65.webp",
        width: 240,
        height: 360,
        bytes: 22666,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-02-card-720.860368b36c.webp",
        width: 720,
        height: 1080,
        bytes: 90254,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-02-raw-512.884760e5ee.webp",
        width: 512,
        height: 512,
        bytes: 36186,
        format: "webp",
      },
    },
  },
  "rune.silver.03": {
    id: "rune.silver.03",
    kind: "rune",
    rarity: "silver",
    name: "井木犴纹",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-03-icon-96.de5b59f0e3.webp",
        width: 96,
        height: 96,
        bytes: 2738,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-03-thumb-240.193deaa6a2.webp",
        width: 240,
        height: 360,
        bytes: 26556,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-03-card-720.84210a9d75.webp",
        width: 720,
        height: 1080,
        bytes: 111514,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-03-raw-512.b55843346c.webp",
        width: 512,
        height: 512,
        bytes: 44012,
        format: "webp",
      },
    },
  },
  "rune.silver.04": {
    id: "rune.silver.04",
    kind: "rune",
    rarity: "silver",
    name: "参水猿箓",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-04-icon-96.ba61168d71.webp",
        width: 96,
        height: 96,
        bytes: 2282,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-04-thumb-240.ee8b000545.webp",
        width: 240,
        height: 360,
        bytes: 20228,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-04-card-720.d3fc9ac57e.webp",
        width: 720,
        height: 1080,
        bytes: 84092,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-04-raw-512.ca32c06629.webp",
        width: 512,
        height: 512,
        bytes: 32872,
        format: "webp",
      },
    },
  },
  "rune.silver.05": {
    id: "rune.silver.05",
    kind: "rune",
    rarity: "silver",
    name: "壁水貐篆",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-05-icon-96.512377a4ea.webp",
        width: 96,
        height: 96,
        bytes: 2540,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-05-thumb-240.19f21e7018.webp",
        width: 240,
        height: 360,
        bytes: 22654,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-05-card-720.1eea81ab05.webp",
        width: 720,
        height: 1080,
        bytes: 94376,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-05-raw-512.2ca67783ec.webp",
        width: 512,
        height: 512,
        bytes: 36122,
        format: "webp",
      },
    },
  },
  "rune.silver.06": {
    id: "rune.silver.06",
    kind: "rune",
    rarity: "silver",
    name: "斗木獬符",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-silver-06-icon-96.9da7496672.webp",
        width: 96,
        height: 96,
        bytes: 2480,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-silver-06-thumb-240.94335f3705.webp",
        width: 240,
        height: 360,
        bytes: 21752,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-silver-06-card-720.0805af6798.webp",
        width: 720,
        height: 1080,
        bytes: 94626,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-silver-06-raw-512.ee2879cc42.webp",
        width: 512,
        height: 512,
        bytes: 35968,
        format: "webp",
      },
    },
  },
  "rune.gold.01": {
    id: "rune.gold.01",
    kind: "rune",
    rarity: "gold",
    name: "武曲贪狼印",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-gold-01-icon-96.20aea497fe.webp",
        width: 96,
        height: 96,
        bytes: 3040,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-gold-01-thumb-240.802c7c8ca4.webp",
        width: 240,
        height: 360,
        bytes: 27188,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-gold-01-card-720.6482b623e5.webp",
        width: 720,
        height: 1080,
        bytes: 122258,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-gold-01-raw-512.665fa0405f.webp",
        width: 512,
        height: 512,
        bytes: 49856,
        format: "webp",
      },
    },
  },
  "rune.gold.02": {
    id: "rune.gold.02",
    kind: "rune",
    rarity: "gold",
    name: "天梁化禄符",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-gold-02-icon-96.02021d5fc7.webp",
        width: 96,
        height: 96,
        bytes: 3032,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-gold-02-thumb-240.84d6d5fe97.webp",
        width: 240,
        height: 360,
        bytes: 26126,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-gold-02-card-720.f13bc5ebfc.webp",
        width: 720,
        height: 1080,
        bytes: 108952,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-gold-02-raw-512.ccc78aca92.webp",
        width: 512,
        height: 512,
        bytes: 48368,
        format: "webp",
      },
    },
  },
  "rune.gold.03": {
    id: "rune.gold.03",
    kind: "rune",
    rarity: "gold",
    name: "紫微帝座铭",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-gold-03-icon-96.661cc8c6c8.webp",
        width: 96,
        height: 96,
        bytes: 3518,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-gold-03-thumb-240.3430d5c604.webp",
        width: 240,
        height: 360,
        bytes: 29550,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-gold-03-card-720.3a0f8055bc.webp",
        width: 720,
        height: 1080,
        bytes: 127696,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-gold-03-raw-512.f2db17b9e2.webp",
        width: 512,
        height: 512,
        bytes: 55678,
        format: "webp",
      },
    },
  },
  "rune.gold.04": {
    id: "rune.gold.04",
    kind: "rune",
    rarity: "gold",
    name: "太阴照命契",
    aspectRatio: 1,
    dominantColor: "#d7a94d",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-gold-04-icon-96.7ecaf3898c.webp",
        width: 96,
        height: 96,
        bytes: 2706,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-gold-04-thumb-240.aa7bf9b481.webp",
        width: 240,
        height: 360,
        bytes: 24574,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-gold-04-card-720.3e9622070c.webp",
        width: 720,
        height: 1080,
        bytes: 98310,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-gold-04-raw-512.8507f61f5c.webp",
        width: 512,
        height: 512,
        bytes: 43362,
        format: "webp",
      },
    },
  },
  "rune.chaos.01": {
    id: "rune.chaos.01",
    kind: "rune",
    rarity: "chaos",
    name: "盘古开天印",
    aspectRatio: 1,
    dominantColor: "#141018",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-chaos-01-icon-96.ff5ccb4739.webp",
        width: 96,
        height: 96,
        bytes: 2800,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-chaos-01-thumb-240.047516f1c9.webp",
        width: 240,
        height: 360,
        bytes: 26144,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-chaos-01-card-720.6b773acf82.webp",
        width: 720,
        height: 1080,
        bytes: 115020,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-chaos-01-raw-512.eb5f4b0f1e.webp",
        width: 512,
        height: 512,
        bytes: 47710,
        format: "webp",
      },
    },
  },
  "rune.chaos.02": {
    id: "rune.chaos.02",
    kind: "rune",
    rarity: "chaos",
    name: "鸿蒙未判契",
    aspectRatio: 1,
    dominantColor: "#141018",
    variants: {
      icon: {
        url: "/api/assets/art/rune/rune-chaos-02-icon-96.6b9077ef6a.webp",
        width: 96,
        height: 96,
        bytes: 3158,
        format: "webp",
      },
      thumb: {
        url: "/api/assets/art/rune/rune-chaos-02-thumb-240.ff9207cb35.webp",
        width: 240,
        height: 360,
        bytes: 29336,
        format: "webp",
      },
      card: {
        url: "/api/assets/art/rune/rune-chaos-02-card-720.7169e38cb4.webp",
        width: 720,
        height: 1080,
        bytes: 133310,
        format: "webp",
      },
      raw: {
        url: "/api/assets/art/rune/rune-chaos-02-raw-512.d64154a2da.webp",
        width: 512,
        height: 512,
        bytes: 55224,
        format: "webp",
      },
    },
  },
  "share.daily": {
    id: "share.daily",
    kind: "share",
    name: "分享卡背景 · daily",
    aspectRatio: 0.5625,
    dominantColor: "#3158d4",
    variants: {
      mobile: {
        url: "/api/assets/art/share/share-daily-mobile-720.4a371374f6.webp",
        width: 720,
        height: 1280,
        bytes: 110362,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/share/share-daily-share-1080.c8a9cef653.webp",
        width: 1080,
        height: 1920,
        bytes: 201456,
        format: "webp",
      },
    },
  },
  "share.seal": {
    id: "share.seal",
    kind: "share",
    name: "分享卡背景 · seal",
    aspectRatio: 0.5625,
    dominantColor: "#3158d4",
    variants: {
      mobile: {
        url: "/api/assets/art/share/share-seal-mobile-720.d3aa2d7847.webp",
        width: 720,
        height: 1280,
        bytes: 204414,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/share/share-seal-share-1080.d0d9b0c076.webp",
        width: 1080,
        height: 1920,
        bytes: 366506,
        format: "webp",
      },
    },
  },
  "share.earn": {
    id: "share.earn",
    kind: "share",
    name: "分享卡背景 · earn",
    aspectRatio: 0.5625,
    dominantColor: "#3158d4",
    variants: {
      mobile: {
        url: "/api/assets/art/share/share-earn-mobile-720.aaf68635cf.webp",
        width: 720,
        height: 1280,
        bytes: 181534,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/share/share-earn-share-1080.29c8ef0efb.webp",
        width: 1080,
        height: 1920,
        bytes: 319260,
        format: "webp",
      },
    },
  },
  "share.box_result": {
    id: "share.box_result",
    kind: "share",
    name: "分享卡背景 · box_result",
    aspectRatio: 0.5625,
    dominantColor: "#3158d4",
    variants: {
      mobile: {
        url: "/api/assets/art/share/share-box-result-mobile-720.4132f97762.webp",
        width: 720,
        height: 1280,
        bytes: 204184,
        format: "webp",
      },
      share: {
        url: "/api/assets/art/share/share-box-result-share-1080.c8aaac9028.webp",
        width: 1080,
        height: 1920,
        bytes: 365792,
        format: "webp",
      },
    },
  },
  "ui.coin": {
    id: "ui.coin",
    kind: "ui",
    name: "UI coin",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/assets/critical/ui/ui-coin-icon-96.a963cabbb7.webp",
        width: 96,
        height: 96,
        bytes: 3560,
        format: "webp",
      },
    },
  },
  "ui.ticket": {
    id: "ui.ticket",
    kind: "ui",
    name: "UI ticket",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/assets/critical/ui/ui-ticket-icon-96.6ed0075171.webp",
        width: 96,
        height: 96,
        bytes: 3128,
        format: "webp",
      },
    },
  },
  "ui.loading_oracle": {
    id: "ui.loading_oracle",
    kind: "ui",
    name: "UI loading_oracle",
    aspectRatio: 1,
    dominantColor: "#3158d4",
    variants: {
      icon: {
        url: "/assets/critical/ui/ui-loading-oracle-icon-96.0b174dbbd7.webp",
        width: 96,
        height: 96,
        bytes: 3106,
        format: "webp",
      },
    },
  },
} as const satisfies AssetManifest;
